ai_signatures:
  - key: "DigitalSourceType"
    value: "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"
  - key: "Software"
    contains: ["Midjourney", "DALL-E", "Stable Diffusion", "Flux"]

aesthetic:
  blur_radius: 20
  thumbnail_quality: 85
  max_width: 2048
  formats: [".jpg", ".jpeg", ".png", ".webp"]

rate_limiting:
  max_entries: 1000
  cleanup_interval: 1m
  entry_ttl: 30m
  trusted_proxies: ["127.0.0.1", "::1"]
  enable_debug: false


